proyectoCuestionario/base/urls.py
from django.conf import settings
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^', include('users.urls', namespace='user')),
    url(r'^', include('cuestionario.urls', namespace='cuestionario')),
]

# If the debug mode is on them debug toolbar urls are included.
if settings.DEBUG:
    import debug_toolbar
    urlpatterns = [
        url(r'^debug-toolbar/', include(debug_toolbar.urls)),
    ] + urlpatterns

proyectoCuestionario/users/urls.py
from django.conf.urls import url
from . import views
from views import (
    RegisterUserView,
    UserListView,
    UserDetailView,
    UserUpdateView,
    UserDeleteView,
    AddUserView,
    Login,
    Register
)

urlpatterns = [
    url(
        r'^$',
        views.index,
        name='index'
    ),
    url(
        r'^login/$',
        views.login_view,
        name='login'
    ),
    url(
        r'^register/$',
        view=RegisterUserView.as_view(),
        name='register'
    ),
    url(
        r'^logout/$',
        view=views.logout_view,
        name='logout'
    ),
    url(
        r'^user_list/$',
        view=UserListView.as_view(),
        name='user-list'
    ),
    url(
        r'^profile/(?P<pk>[^\/]+)/$',
        view=UserDetailView.as_view(),
        name='profile'
    ),
    url(
        r'^profile/edit/(?P<pk>[^\/]+)/$',
        view=UserUpdateView.as_view(),
        name='profile-update'
    ),
    url(
        r'^profile/delete/(?P<pk>[^\/]+)/$',
        view=UserDeleteView.as_view(),
        name='profile-delete'
    ),
    url(
        r'^add_User/$',
        view=AddUserView.as_view(),
        name='add-user'
    ),
    url(
        r'^login_angular/$',
        view=Login.as_view(),
        name='login_angular'
    ),
    url(
        r'^register_angular/$',
        view=Register.as_view(),
        name='register_angular'
    ),
]

proyectoCuestionario/users/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models
from django.contrib.auth.models import AbstractUser

# Create your models here.


class User(AbstractUser):
    name = models.CharField(max_length=100, blank=True, null=True)

proyectoCuestionario/users/forms.py
# -*- coding: utf-8 -*-

# future
from __future__ import unicode_literals

# Django
from django import forms
from django.contrib.auth import authenticate, get_user_model
from django.utils.translation import ugettext_lazy as _


class UserLoginForm(forms.Form):
    """
    Display the login form.
    """

    _user = None

    username = forms.CharField(label=('Username'))
    password = forms.CharField(widget=forms.PasswordInput, label=('Password'))

    def authenticate_user(self):
        username = self.cleaned_data.get('username', False)
        password = self.cleaned_data.get('password', False)

        if username and password:
            user = authenticate(username=username, password=password)

            if not user:
                raise forms.ValidationError("This user does not exist")
            if not user.check_password(password):
                raise forms.ValidationError("Incorrect password")

            if user is not None:
                self._user = user
                return True

        return False

    def clean(self):
        found = self.authenticate_user()

        if not found:
            raise Exception()

    def get_user(self):
        return self._user


class RegisterUserForm(forms.ModelForm):
    """
    Display the register form.
    """

    password = forms.CharField(label=_("Password"),
                               widget=forms.PasswordInput)
    password2 = forms.CharField(label=_("Password confirmation"),
                                widget=forms.PasswordInput)

    class Meta:
        model = get_user_model()
        fields = ['username', 'email']

    def clean_password2(self):
        password = self.cleaned_data.get("password")
        password2 = self.cleaned_data.get("password2")

        if password and password2 and password != password2:
            raise forms.ValidationError(u"Passwords do not match.")

        return password2


class UserUpdateForm(forms.ModelForm):
    """
    Display the user update form.
    """

    class Meta:
        model = get_user_model()
        fields = ['email', 'first_name', 'last_name']

    def clean(self, *args, **kwargs):
        cleaned_data = super(UserUpdateForm, self).clean(*args, **kwargs)
        return cleaned_data


class AddUserForm(forms.ModelForm):
    """
    Display the user add form.
    """
    class Meta:
        model = get_user_model()
        fields = ['email', 'first_name', 'last_name', 'username']

    def clean(self, *args, **kwargs):
        cleaned_data = super(AddUserForm, self).clean(*args, **kwargs)
        return cleaned_data

proyectoCuestionario/users/views.py
# -*- coding: utf-8 -*-

# future
from __future__ import unicode_literals

# Django
from django.contrib.auth import (authenticate, get_user_model, login, logout)
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import (
    LoginRequiredMixin
)
from django.shortcuts import render, redirect
from django.views.generic import (
    CreateView,
    DetailView,
    UpdateView,
    ListView,
    DeleteView)
from django.utils.translation import gettext as _
from django.urls import reverse_lazy

# Rest_Framework
from rest_framework import parsers, status, renderers
from rest_framework.authtoken.models import Token
from rest_framework.views import APIView
from rest_framework.response import Response
from rest_framework.authtoken.views import ObtainAuthToken

# Local Django
from base.mixin import StaffRequiredMixin, UserPerfilMixin

from .forms import (
    UserLoginForm,
    RegisterUserForm,
    UserUpdateForm,
    AddUserForm
)

from .models import User

from .serializers import (
    AuthCustomTokenSerializer,
    UsersSerializer
)


@login_required
def index(request):
    """
    Display the index page.
    """

    model = get_user_model()
    return render(request, 'users/index.html')


def login_view(request):
    """
    Display the login form and handle the login action.
    """
    form = UserLoginForm()

    if request.method == 'POST':
        form = UserLoginForm(request.POST)

        if form.is_valid():
            user = form.get_user()
            login(request, user)
        return redirect('user:index')
    else:
        form = UserLoginForm()

    return render(request, "users/form.html", {"form": form})


class RegisterUserView(CreateView):
    """
    Display the register form and handle the register action.
    """

    form_class = RegisterUserForm
    template_name = "users/register.html"

    def form_valid(self, form):

        user = form.save(commit=False)
        password = form.cleaned_data.get('password', False)
        if password:
            user.set_password(password)
            user.save()
            new_user = authenticate(username=user, password=password)
            login(self.request, new_user)
            return redirect('user:index')


def logout_view(request):
    """
    Handle the logout action.
    """

    logout(request)
    return redirect('user:login')


class AddUserView(StaffRequiredMixin, CreateView):
    """
    Display the add new user form by admin and handle the new register action.
    """

    form_class = AddUserForm
    template_name = 'users/add_user.html'

    def form_valid(self, form):
        user = form.save(commit=False)
        if form.cleaned_data:
            user.save()
            return redirect('user:user-list')


class UserListView(StaffRequiredMixin, ListView):
    """
    Display user list.
    """

    model = get_user_model()
    template_name = 'users/user_list.html'


class UserDetailView(LoginRequiredMixin, DetailView):
    """
    Display user details.
    """

    model = get_user_model()
    template_name = 'users/profile.html'


class UserUpdateView(LoginRequiredMixin, UserPerfilMixin, UpdateView):
    """
    Handle user update action.
    """

    model = get_user_model()
    form_class = UserUpdateForm
    template_name = "users/user_update.html"
    success_url = 'user:profile'

    def get_success_url(self):
        return reverse_lazy(
            self.success_url, kwargs={'pk': self.object.id})


class UserDeleteView(StaffRequiredMixin, DeleteView):
    """
    Handle user delete action.
    """

    model = get_user_model()
    template_name = "users/user_delete.html"
    success_url = reverse_lazy('user:user-list')


class Login(ObtainAuthToken, APIView):
    """
    Display the login form and handle the register action with Angular v4.
    """

    serializer_class = AuthCustomTokenSerializer

    def post(self, request, *args, **kwargs):
        serializer = self.serializer_class(data=request.data)
        serializer.is_valid(raise_exception=True)

        if serializer.is_valid():
            user = serializer.data['user']
            password = serializer.data['password']
            new_user = authenticate(username=user, password=password)

            if new_user:
                token, created = Token.objects.get_or_create(
                    user=new_user)

                return Response(
                    {
                        'created': created,
                        'token': token.key,
                    }
                )
            else:
                content = {
                    'detail': _('Unable to login with provided credentials.')
                }
                return Response(content, status=status.HTTP_401_UNAUTHORIZED)

        else:
            return Response(
                serializer.errors,
                status=status.HTTP_400_BAD_REQUEST
            )


class Register(ObtainAuthToken, APIView):
    """
    Display the register form and handle the register action with Angular v4.
    """

    serializer_class = UsersSerializer

    def post(self, request, *args, **kwargs):
        serializer = self.serializer_class(data=request.data)
        serializer.is_valid(raise_exception=True)

        if serializer.is_valid():
            user = serializer.data['user']
            password = serializer.data['password']
            password2 = serializer.data['password2']

            if password and password2 and password != password2:
                content = {
                    'detail': _('Passwords do not match.')
                }
                return Response(content, status=status.HTTP_401_UNAUTHORIZED)
            else:
                new_user = User(username=user)
                new_user.set_password(password)
                new_user.save()
                new_auth = authenticate(username=user, password=password)

                if new_auth:
                    token, created = Token.objects.get_or_create(
                        user=new_auth)

                    return Response(
                        {
                            'created': created,
                            'token': token.key,
                        }
                    )
                else:
                    content = {
                        'detail': _('Unable to login with provided credentials.')
                    }
                    return Response(content,
                                    status=status.HTTP_401_UNAUTHORIZED)

        else:
            return Response(
                serializer.errors,
                status=status.HTTP_400_BAD_REQUEST
            )

proyectoCuestionario/users/templates/users/add_user.html
{% extends 'base.html' %}
{% load static %}
{% load bootstrap4 %}

{% block  page_title %} Add User {% endblock %}

	{% block main_content %}
		<div class="container">
			<div class="container-margin">
				<div class="row justify-content-center">
					<div class="card card-width">
						<div class="card-header">
	    					<h3> Add New User</h3>
	  					</div>
	  					<div class="card-block">
							<form action="{% url 'user:add-user' %}" method="post">
								<div class="row">
							    	<div class="col-md-7">
		  								<div class="col-12">
				  							<div class="side-left">
				  							{% csrf_token %}
				  								{% bootstrap_field form.username show_help=False form_group_class="form-group-register" %}

												{% bootstrap_field form.first_name show_help=False form_group_class="form-group-register" %}

												{% bootstrap_field form.last_name show_help=False form_group_class="form-group-register" %}

												{% bootstrap_field form.email show_help=False form_group_class="form-group-register" %}
											</div>
										</div>
									</div>
									<div class="col-md-5">
										<div class="col-12">
											<div class="side-right">
												<img src="/base/static/img/turpial_isotipo-03.png" class="img-circle" alt="" width="304" height="236"> 
											</div>
										</div>
									</div>
								</div>
								<br>
								<div class="row">
									<div class="col-md-4">
									</div>
									<div class="col-md-4">
										<button type="submit" value="Update" class="btn btn-block btn-success button-register">Create User</button>
									</div>
								</div>
							</form>
						</div>
					</div>
				</div>
			</div>
		</div>
	{% endblock %}

proyectoCuestionario/users/templates/users/form.html
{% extends 'base.html' %}
{% load static %}
{% load bootstrap4 %}

	{% block  page_title %} Login {% endblock %}
	
	{% block main_content %}
		<div class="container">
			<div class="container-margin">
				<div class="row justify-content-center">
				    <div class="col-md-8">
						<div class="card-group mb-0">
							<div class="card p-4 card-signin">
								<div class="card-body">
									<h1>Login</h1>
									<p class="text-muted"> Sign In your account</p>
									<form method="post">
										{% csrf_token %}
										<div class="input-group mb-3">
											<span class="input-group-addon">
												<i class="icon-user"></i>
											</span>
											{% bootstrap_field form.username show_label=False form_group_class="" %}
										</div>
										<div class="input-group mb-4">
											<span class="input-group-addon">
												<i class="icon-lock"></i>
											</span>
											{% bootstrap_field form.password show_label=False  form_group_class=""%}
										</div>
										<div class="row">
											<div class="col-6">
												<button  class="btn btn-primary px-4 button-signin" type="submit">Login</button>
											</div>
											<div class="col-6 text-right">
												<button  class="btn btn-link px-0" type="button">Forgot password?</button>
											</div>
										</div>	
									</form>
								</div>	
							</div>
							<div class="card text-white bg-primary py-5 d-md-down-none card-signup">
								<div class="card-body text-center">
									<div>
										<h2>Sign up</h2>
										<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.</p>
										<!-- <button type="button" class="btn btn-primary mt-3 button-signup">Register Now!</button> -->
										<a href="{% url 'user:register' %}" class="btn btn-primary mt-3 button-signup" role="button">Register Now!</a>
									</div>
								</div>							
							</div>	
						</div>
					</div>
				</div>
			</div>
		</div>
	{% endblock %}

proyectoCuestionario/users/templates/users/index.html
{% extends 'base.html' %}
{% load static %}
{% load bootstrap4 %}
{%load staticfiles %}

    {% block  page_title %} Index {% endblock %}
    {% block main_content %}
        <div id="wrapper" class="toggled">
            <!--- Sidebar -->
            <div id="sidebar-wrapper">
                <ul class="sidebar-nav text-center">
                    <a href="{% url 'user:profile' user.id %}">
                        <div class="circle"></div>
                    </a>
                    <li>
                        <h3> {{ user.username }}</h3>
                    </li>
                    <li>
                        <h4>  {{ user.last_name }}, {{ user.first_name }} </h4>
                    </li>
                    <li>
                        <h5> Departamento</h5>
                    </li>
                    <div class="icons-user-list">
                        {% if user.is_superuser %}
                                <a id="icon-user" href="{% url 'user:add-user' %}"><i class="icon-user"></i>ADD USER</a>
                                <br>
                                <a id="icon-list" href="{% url 'user:user-list' %}"><i class="icon-list"></i>USER LIST</a>
                        {% endif %}
                    </div>    
                    <br>
                    <div class="icon-logout-padding">
                        <a id="icon-logout" href="{% url 'user:logout' %}"><i class="icon-logout"></i> SALIR</a>  
                    </div>
                        
                </ul>
            </div>
            <!--- Sidebar Wrapper -->

            <!--- Page Content -->
            <div class="jumbotron jumbotron-fluid bg-info text-black text-center index">
                <div class="container">
                    <h1 class="display-1 text-center-welcome"> Welcome</h1>
                </div>
            </div>
        </div>
        <!--- /#wrapper -->
    {% endblock %}

proyectoCuestionario/users/templates/users/profile.html
{% extends 'base.html' %}
{% load static %}
{% load bootstrap4 %}

{% block  page_title %} Profile {% endblock %}

{% block main_content %}
	<div class="container">
		<div class="container-margin">
			<div class="row justify-content-center">
				<div class="card card-width">
					<div class="card-header">
	    				<h3>{{ user.username }}</h3>
	  				</div>
	  				<div class="card-block">
	  					<div class="row">
	  						<div class="col-md-7">
	  							<div class="col-12">
			  						<div class="side-left">
										<p>First Name : {{ user.first_name }}</p>
										<p>Last Name : {{ user.last_name }}</p>
										<p>Email : {{ user.email }}</p>
										<p>Date Joined : {{ user.date_joined }}</p>
									</div>
								</div>
							</div>
							<div class="col-md-5">
								<div class="col-12">
									<div class="side-right">
										<img src="/base/static/img/turpial_isotipo-03.png" class="img-circle" alt="" width="304" height="236"> 
									</div>
								</div>
							</div>
	  					</div>
	  					{% if  request.user.username == user.username %}
		  					<div class="row">
								<div class="col-md-4">
								</div>
								<div class="col-md-4">
									<a href="{% url 'user:profile-update' user.id %}" class="btn btn-block btn-success mt-3" role="button">Edit Profile</a>
								</div>
							</div>
						{% endif %}
					</div>
				</div>

			</div>
			<div class="row">
				<div class="col-md-4">
				</div>
				<div class="col-md-4">
					<a href="{% url 'user:user-list' %}" class="btn btn-info mt-3 button-back" role="button">Back</a>
				</div>
			</div>
		</div>
	</div>
{% endblock %}

proyectoCuestionario/users/templates/users/register.html
{% extends 'base.html' %}
{% load static %}
{% load bootstrap4 %}

{% block  page_title %} Register {% endblock %}

{% block main_content %}
	<div class="container">
		<div class="container-margin">
			<div class="row justify-content-center">
				<div class="col-md-6">
					<div class="card card-signin mx-4">
				 		<div class="card-body p-4">
				 			<h1>Register</h1>
				 			<p class="text-muted">Create your account</p>
				 			<form method="post">
								{% csrf_token %}
					 			<div class="input-group mb-3">
		              				<span class="input-group-addon"><i class="icon-user"></i></span>
		              				{% bootstrap_field form.username show_label=False show_help=False form_group_class="form-group-register" %}
		            			</div>
		            			<div class="input-group mb-3">
		              				<span class="input-group-addon">@</span>
		              				{% bootstrap_field form.email show_label=False form_group_class="form-group-register" %}
		            			</div>
		            			<div class="input-group mb-3">
		              				<span class="input-group-addon"><i class="icon-lock"></i></span>
		              				{% bootstrap_field form.password show_label=False form_group_class="form-group-register" %}
		            			</div>
		            			<div class="input-group mb-4">
		              				<span class="input-group-addon"><i class="icon-lock"></i></span>
		              				{% bootstrap_field form.password2 show_label=False form_group_class="form-group-register" %}
		            			</div>
		            			<button type="submit" value="Register" class="btn btn-block btn-success button-register">Create Account</button>
		            		</form>
						</div>
					</div>
				</div>
			</div>
		</div>	
	</div>
{% endblock %}

proyectoCuestionario/users/templates/users/user_delete.html
{% extends 'base.html' %}
{% load static %}
{% load bootstrap4 %}

{% block  page_title %} Delete {% endblock %}

	{% block main_content %}
		<div class="container">
			<div class="container-margin">
				<div class="row justify-content-center">
					<div class="card card-width">
						<div class="card-header">
	    					<h3> Delete User </h3>
	  					</div>
	  					<div class="card-block">
							<form action="" method="post">
								<div class="row">
									{% csrf_token %}
							    	<div class="col-md-2">
		  								
									</div>
									<div class="col-md-8">
		  								<h5>Deleting User <b>{{ user.username }} </b> will remove all his information from our database. This can't be undone </h5>
									</div>
								</div>
								<br>
								<div class="row">
									<div class="col-md-4">
									</div>
									<div class="col-md-4">
										<button type="submit" value="Update" class="btn btn-block btn-danger button-register">Delete</button>
									</div>
								</div>
							</form>
						</div>
					</div>
				</div>
			</div>
		</div>
	{% endblock %}

proyectoCuestionario/users/templates/users/user_list.html
{% extends 'base.html' %}
{% load static %}
{% load bootstrap4 %}

{% block  page_title %} User List {% endblock %}

	{% block main_content %}
			<div class="container title-table">
				<div class="container-margin">
					<div class="row justify-content-left">
						<h1>User List</h1>
						<table class="table table-striped table-bordered"> 
							<thead>
								<tr>
  									<th> Username </th>
  									<th> Date registered </th>
  									<th> Staff </th>
  									<th> Status </th>
  									<th></th>
								</tr>
							</thead>
							<tbody>
								{% for user in object_list %}
									<tr>
										<td> 
											<a href="{% url 'user:profile' user.id %}"> {{ user.username }} </a>
										</td>
										<td> {{ user.date_joined }} </td>
										<td> 
											{% if user.is_superuser %}
												<span class="input-group-addon span-width ">
													<i class="icon-check"></i>
												</span>
											{% else %}
												<span class="input-group-addon span-width">
													<i class="icon-close"></i>
												</span>
											{% endif %}
										</td>
										<td> 
											{% if user.is_active %}
												<span class="input-group-addon span-width">
													<i class="icon-check"></i>
												</span>
											{% else %}
												<span class="input-group-addon span-width">
													<i class="icon-close"></i>
												</span>
											{% endif %} 
										</td>
										<td><a href="{% url 'user:profile-delete' user.id %}"> Delete </a> </td>
									</tr>
								{% endfor %}
							</tbody>
						</table>
					</div>
				</div>
			</div>
	{% endblock %}

proyectoCuestionario/users/templates/users/user_update.html
{% extends 'base.html' %}
{% load static %}
{% load bootstrap4 %}

{% block  page_title %} Edit {% endblock %}

	{% block main_content %}
		<div class="container">
			<div class="container-margin">
				<div class="row justify-content-center">
					<div class="card card-width">
						<div class="card-header">
	    					<h3>{{ user.username }}</h3>
	  					</div>
	  					<div class="card-block">
							<form action="{% url 'user:profile-update' user.id %}" method="post">
								<div class="row">
									
							    	<div class="col-md-7">
		  								<div class="col-12">
				  							<div class="side-left">
				  							{% csrf_token %}
												{% bootstrap_field form.first_name show_help=False form_group_class="form-group-register" %}

												{% bootstrap_field form.last_name show_help=False form_group_class="form-group-register" %}

												{% bootstrap_field form.email show_help=False form_group_class="form-group-register" %}
											</div>
										</div>
									</div>
									<div class="col-md-5">
										<div class="col-12">
											<div class="side-right">
												<img src="/base/static/img/turpial_isotipo-03.png" class="img-circle" alt="" width="304" height="236"> 
											</div>
										</div>
									</div>
								</div>
								<br>
								<div class="row">
									<div class="col-md-4">
									</div>
									<div class="col-md-4">
										<button type="submit" value="Update" class="btn btn-block btn-success button-register">Save</button>
									</div>
								</div>
							</form>
						</div>
					</div>
				</div>
			</div>
		</div>
	{% endblock %}